#!/usr/bin/env ruby
require 'net/smtp'

def email(body, subject, toList, smtpFrom="foo@example.com", smtpServer="smtp.example.com")
  raise "No email body" unless body and not body.empty?
  raise "No TO list" unless toList and not toList.empty?

  msgstr= <<END_OF_MSG
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
From: #{smtpFrom}
To: #{toList.join(',')}
Subject: #{subject}

#{body}
END_OF_MSG

  puts "Sending mail to #{toList.join(',')}..."
  Net::SMTP.start(smtpServer) do |smtp|
    smtp.send_message msgstr, smtpFrom, toList
  end 
end

error do
  subject = "Krampus is angry!"
  body = "Exception in route: " + env['sinatra.error'].message
  body += "\n\n"
  body += env['sinatra.error'].backtrace
  body += "\n\n-- \n"
  body += "This email generated by #{__FILE__}, on #{$hostname}."
  email(body, subject, $maintainers)
end

